version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu2204

init:
  # as its not possible to use docker as source image, we will install everything in init step
  - >
    sudo apt-get update --allow-releaseinfo-change &&
    sudo apt-get install -y g++-mingw-w64-x86-64 g++-mingw-w64-i686 unzip wget man2html-base groff
  # NSIS 3.08-3 from Debian 12 generates bogus relocation information (regression).
  # The fixed version 3.09-1 is still only available from Ubuntu 23.10 (mantic, devel).
  # Manually install this version.  The warning about outdated libstdc++6 could be
  # safely ignored.
  - >
    wget http://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis_3.09-4ubuntu1_amd64.deb -O /tmp/nsis_3.09-4ubuntu1_amd64.deb &&
    wget http://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis-common_3.09-4ubuntu1_all.deb -O /tmp/nsis-common_3.09-4ubuntu1_all.deb
    && sudo dpkg --install --force-all /tmp/nsis-common_3.09-4ubuntu1_all.deb /tmp/nsis_3.09-4ubuntu1_amd64.deb

build_script:
- cd smartmontools
- export SOURCE_DATE_EPOCH=$(git log -1 --format="%at")
- SM_VER=$(grep -E 'AC_INIT\(\[smartmontools\]' configure.ac|awk -F, '{print $2}'|tr -d '[]')
- sh: "SVNREV=$(git log -1|grep -oP 'git-svn-id: http://svn.code.sf.net/p/smartmontools/code/trunk@(\\d+)'|awk -F@ '{print $2}')"
- BUILD_INFO='"(AppVeyor)"'
- 'echo "Starting build: SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH}, SM_VER: ${SM_VER}, SVNREV: ${SVNREV}"'
- ./autogen.sh && mkdir build && cd build
- ../configure build_alias=$(../config.guess) host_alias=i686-w64-mingw32 SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
- make -j BUILD_INFO="$BUILD_INFO" && make distdir-win32 && cd .. && mkdir build64 && cd build64
- ../configure build_alias=$(../config.guess) host_alias=x86_64-w64-mingw32 SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
- make -j BUILD_INFO="$BUILD_INFO" && make distdir-win32
- cd ../build && dest="smartmontools-win32-setup-${SM_VER}-r${SVNREV}.exe"
- make BUILD_INFO="$BUILD_INFO" builddir_win64=../build64 distinst_win32="$dest" installer-win32
- sha256sum *.exe
# - cd /home/appveyor/projects/smartmontools-fork/ && zip build.zip smartmontools -r

artifacts:
- path: smartmontools/build/smartmontools-win32-setup-*.exe
# - path: build.zip

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/0924a018-22d7-47ea-b10c-7c84c08e8d55/Integrations/AppVeyor?ProjectSlug=smartmontools&SigningPolicySlug=release-signing
  authorization:
     secure: Y7K0hTnpfEyXhOI/cG1URZwss24IjRECus4em8YscdJ73ujuXg/CRkdBa0eOoAZc7hUa+qo6rGOy/ii9iHE0zA==
